// <auto-generated />
using System;
using DATN_API.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DATN_API.Data.Migrations
{
    [DbContext(typeof(DATNDbContext))]
    partial class DATNDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DATN_API.Data.Entities.ChiTietDonHang", b =>
                {
                    b.Property<int>("IdChiTietDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("GiaMua")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdDonHang")
                        .HasColumnType("int");

                    b.Property<int>("IdMauSanPham")
                        .HasColumnType("int");

                    b.Property<int>("IdSanPham")
                        .HasColumnType("int");

                    b.Property<int>("IdSizeSanPham")
                        .HasColumnType("int");

                    b.Property<int?>("SanPhamIdSanPham")
                        .HasColumnType("int");

                    b.Property<int?>("SizeSanPhamIdSizeSanPham")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("IdChiTietDonHang");

                    b.HasIndex("IdDonHang");

                    b.HasIndex("IdMauSanPham");

                    b.HasIndex("SanPhamIdSanPham");

                    b.HasIndex("SizeSanPhamIdSizeSanPham");

                    b.ToTable("ChiTietDonHang");
                });

            modelBuilder.Entity("DATN_API.Data.Entities.ChiTietHoaDonNhap", b =>
                {
                    b.Property<int>("IdChiTietHoaDonNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdHoaDonNhap")
                        .HasColumnType("int");

                    b.Property<int>("IdMauSanPham")
                        .HasColumnType("int");

                    b.Property<int>("IdSanPham")
                        .HasColumnType("int");

                    b.Property<int>("IdSizeSanPham")
                        .HasColumnType("int");

                    b.Property<int?>("SanPhamIdSanPham")
                        .HasColumnType("int");

                    b.Property<int?>("SizeSanPhamIdSizeSanPham")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("IdChiTietHoaDonNhap");

                    b.HasIndex("IdHoaDonNhap");

                    b.HasIndex("IdMauSanPham");

                    b.HasIndex("SanPhamIdSanPham");

                    b.HasIndex("SizeSanPhamIdSizeSanPham");

                    b.ToTable("ChiTietHoaDonNhap");
                });

            modelBuilder.Entity("DATN_API.Data.Entities.DanhMuc", b =>
                {
                    b.Property<int>("IdDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IdDanhMucCha")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("IdDanhMuc");

                    b.ToTable("DanhMuc");
                });

            modelBuilder.Entity("DATN_API.Data.Entities.DonHang", b =>
                {
                    b.Property<int>("IdDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChiGiaoHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IdKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiDonHang")
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("IdDonHang");

                    b.HasIndex("IdKhachHang");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("DATN_API.Data.Entities.HoaDonNhap", b =>
                {
                    b.Property<int>("IdHoaDonNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IdNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("IdNhaCungCap")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("TongTien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrangThaiHoaDonNhap")
                        .HasColumnType("int");

                    b.HasKey("IdHoaDonNhap");

                    b.HasIndex("IdNhaCungCap");

                    b.ToTable("HoaDonNhap");
                });

            modelBuilder.Entity("DATN_API.Data.Entities.KhachHang", b =>
                {
                    b.Property<int>("IdKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DiaChiGiaoHang")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("IdKhachHang");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("DATN_API.Data.Entities.KhuyenMai", b =>
                {
                    b.Property<int>("IdKhuyenMai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MaKhuyenMai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("ntext");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PhanTramGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenKhuyenMai")
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("IdKhuyenMai");

                    b.ToTable("KhuyenMai");
                });

            modelBuilder.Entity("DATN_API.Data.Entities.MauSanPham", b =>
                {
                    b.Property<int>("IdMauSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AnhSanPham")
                        .HasColumnType("varchar(500)");

                    b.Property<int>("CheckThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal");

                    b.Property<int>("IdSanPham")
                        .HasColumnType("int");

                    b.Property<string>("MaMau")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TenMau")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("IdMauSanPham");

                    b.HasIndex("IdSanPham");

                    b.ToTable("MauSanPham");
                });

            modelBuilder.Entity("DATN_API.Data.Entities.News", b =>
                {
                    b.Property<int>("IdNews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Anh")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("LoaiTin")
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayDang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdNews");

                    b.ToTable("News");
                });

            modelBuilder.Entity("DATN_API.Data.Entities.NhaCungCap", b =>
                {
                    b.Property<int>("IdNhaCungCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SDT")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("IdNhaCungCap");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("DATN_API.Data.Entities.NhanVien", b =>
                {
                    b.Property<int>("IdNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayVaoLam")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("IdNhanVien");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("DATN_API.Data.Entities.SanPham", b =>
                {
                    b.Property<int>("IdSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AnhSanPham")
                        .HasColumnType("varchar(500)");

                    b.Property<int>("IdDanhMuc")
                        .HasColumnType("int");

                    b.Property<int>("IdThuongHieu")
                        .HasColumnType("int");

                    b.Property<string>("MoTaSanPham")
                        .HasColumnType("ntext");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("IdSanPham");

                    b.HasIndex("IdDanhMuc");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("DATN_API.Data.Entities.SizeSanPham", b =>
                {
                    b.Property<int>("IdSizeSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdMauSanPham")
                        .HasColumnType("int");

                    b.Property<int>("IdSanPham")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("IdSizeSanPham");

                    b.HasIndex("IdMauSanPham");

                    b.ToTable("SizeSanPham");
                });

            modelBuilder.Entity("DATN_API.Data.Entities.ThuongHieu", b =>
                {
                    b.Property<int>("IdThuongHieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MoTa")
                        .HasColumnType("ntext");

                    b.Property<string>("TenThuongHieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("IdThuongHieu");

                    b.ToTable("ThuongHieu");
                });

            modelBuilder.Entity("DATN_API.Data.Entities.ChiTietDonHang", b =>
                {
                    b.HasOne("DATN_API.Data.Entities.DonHang", "DonHang")
                        .WithMany()
                        .HasForeignKey("IdDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN_API.Data.Entities.MauSanPham", "MauSanPham")
                        .WithMany()
                        .HasForeignKey("IdMauSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN_API.Data.Entities.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamIdSanPham");

                    b.HasOne("DATN_API.Data.Entities.SizeSanPham", "SizeSanPham")
                        .WithMany()
                        .HasForeignKey("SizeSanPhamIdSizeSanPham");
                });

            modelBuilder.Entity("DATN_API.Data.Entities.ChiTietHoaDonNhap", b =>
                {
                    b.HasOne("DATN_API.Data.Entities.HoaDonNhap", "HoaDonNhap")
                        .WithMany()
                        .HasForeignKey("IdHoaDonNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN_API.Data.Entities.MauSanPham", "MauSanPham")
                        .WithMany()
                        .HasForeignKey("IdMauSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN_API.Data.Entities.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamIdSanPham");

                    b.HasOne("DATN_API.Data.Entities.SizeSanPham", "SizeSanPham")
                        .WithMany()
                        .HasForeignKey("SizeSanPhamIdSizeSanPham");
                });

            modelBuilder.Entity("DATN_API.Data.Entities.DonHang", b =>
                {
                    b.HasOne("DATN_API.Data.Entities.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DATN_API.Data.Entities.HoaDonNhap", b =>
                {
                    b.HasOne("DATN_API.Data.Entities.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("IdNhaCungCap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DATN_API.Data.Entities.MauSanPham", b =>
                {
                    b.HasOne("DATN_API.Data.Entities.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("IdSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DATN_API.Data.Entities.SanPham", b =>
                {
                    b.HasOne("DATN_API.Data.Entities.DanhMuc", "DanhMuc")
                        .WithMany()
                        .HasForeignKey("IdDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DATN_API.Data.Entities.SizeSanPham", b =>
                {
                    b.HasOne("DATN_API.Data.Entities.MauSanPham", "MauSanPham")
                        .WithMany()
                        .HasForeignKey("IdMauSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
